<section>
    <h1>About</h1>

    <p>
        The reconstructions currently available for viewing include data generated using a Bayesian proxy data assimilation method, which starts with a climate model prior
        and is updated using a global database of proxy observations, including the PAGES2k database and additional ice core and coral records. Each reconstruction
        is named after its climate model prior, which uses different native climate models and/or forcings. The climate model priors influence two key components:
        the range of prior states available, and the covariance structures between variables (which affects the weighting given to each proxy record).
    </p>

    <p>
        The CESM1 and HadCM3 reconstructions are generated by 
        <a href="https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2021GL095999" target="_blank" rel="noreferrer" class="underline">O'Connor et al., 2021</a>.
        Refer to O'Connor et al., 2021 for full details on the methodology. The netCDF files for the O'Connor et al., 2021 reconstructions are available for download at 
        <a href="https://zenodo.org/records/5507607#.Y6OMWuyIb0o" target="_blank" rel="noreferrer" class="underline">Zenodo</a>. 
        The updated CESM2 reconstructions are generated by O'Connor et al., in review and will be available for download upon publication. 
    </p>

    <p>
        This web app was developed by Gemma O'Connor and Jordan Tucker. Initial release in September 2024. 
    </p>
</section>

<style>
    p {
        margin-bottom: 20px;
    }
</style>





