<section class="page">
    <h1>About</h1>

    <p>
        The reconstructions currently available for viewing include data generated using a Bayesian proxy data assimilation method, which starts with a climate model prior
        and is updated using a global database of proxy observations, including the PAGES2k database and additional ice core and coral records. Each reconstruction
        is named after its climate model prior, which uses different native climate models and/or forcings. The climate model priors influence two key components in the assimilation 
        method: the range of prior states available, and the covariance structures between variables (which affects the weighting given to each proxy record).
    </p>

    <p>
        Ideally, we would have an expansive global database of proxy records with minimal uncertainty. If this were the case, all of the reconstructions would converge to a similar 
        reconstruction state -- regardless of the climate model prior used. Because we do not have perfect proxy observations available, the reconstructions generated with different 
        priors have several differences. In regions where climate models have high confidence in their ability to simulate the climate, and in regions where the proxies provide
        excellent coverage, the reconstructions have small uncertainty. Some climate model priors result in more skillful reconstructions (i.e., better agreement with instrumental data)
        in certain regions, but not in others. There is no one-size-fits-all reconstruction that is best for all paleoclimate questions. This web app allows you to easily compare 
        these differences at different locations that are of interest to you.
    </p>

    <p>
        The CESM1 and HadCM3 reconstructions are generated by 
        <a href="https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2021GL095999" target="_blank" rel="noreferrer" class="underline">O'Connor et al., 2021</a>.
        Refer to O'Connor et al., 2021 for full details on the methodology. The netCDF files for the O'Connor et al., 2021 reconstructions are available for download at 
        <a href="https://zenodo.org/records/5507607#.Y6OMWuyIb0o" target="_blank" rel="noreferrer" class="underline">Zenodo</a>. 
        The updated CESM2 reconstructions are generated by O'Connor et al., in review and will be available for download upon publication. 
    </p>

    <p>
        This web app was developed by Jordan Tucker and Gemma O'Connor at the University of Washington, with funding from the UW eScience Institute for data science. 
        Initial release September 2024. 
    </p>
</section>

<style>
    /* Add margin to the sides of the page */
    .page {
        margin: 0 auto; /* centers the content */
        max-width: 1200px; /* set a max width for the page content */
        padding: 20px;
    }

    /* Style the header */
    h1 {
        font-size: 2.5rem; /* Increase header font size */
        margin-bottom: 20px;
    }

    /* Style the paragraphs */
    p {
        margin-bottom: 20px;
    }

    /* Style the links */
    a.underline {
        text-decoration: underline;
    }
</style>
